# Database connection
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/auxim_db

# Auto-create tables 
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false

# Restate Engine URL 
quarkus.rest-client.restate-api.url=http://localhost:8080

quarkus.hibernate-orm.mapping.format.global=ignore

quarkus.http.port=8081